# Generated by Django 5.1.4 on 2024-12-24 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0004_coursepayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.PositiveIntegerField(default=1000, verbose_name='Цена'),
        ),
    ]
