# Generated by Django 5.1.4 on 2024-12-25 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0005_course_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CoursePayment',
        ),
    ]
