# Generated by Django 5.1.4 on 2024-12-25 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0006_delete_coursepayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='price',
            field=models.PositiveIntegerField(default=1000, verbose_name='Цена'),
        ),
    ]
